-- Conectado como SYS o SYSTEM
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER PRUEBA IDENTIFIED BY PRUEBA
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE
TO PRUEBA;

