ALTER SESSION SET CONTAINER = XEPDB1;
-- Esquema de prueba
ALTER SESSION SET CURRENT_SCHEMA = PRUEBA;

-- Tabla de categorías
CREATE TABLE categorias (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL,
    activa      NUMBER(1) DEFAULT 1
);

-- Tabla de personas
CREATE TABLE personas (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(100) NOT NULL,
    categoria_id  NUMBER,
    estado        NUMBER(1) NOT NULL,
    CONSTRAINT fk_persona_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categorias(id)
);

-- Tabla para la parte de NULLs
CREATE TABLE pagos (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto  NUMBER(10,2)
);
